version: '3'
services:
  foundryvtt:
    container_name: foundryvtt
    image: shoyuvanilla/foundryvtt
    restart: always
    volumes:
      - ./foundryvtt:/foundryvtt
      - ./foundrydata:/root/.local/share/FoundryVTT

  tinyfilemanager:
    container_name: tinyfilemanager
    image: shoyuvanilla/tinyfilemanager-forfvtt
    restart: always
    volumes:
      - ./:/data
      - ./tinyfilemanager-config.json:/config.json

  https-portal:
    container_name: https-portal
    image: steveltn/https-portal
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      STAGE: production
      PROXY_READ_TIMEOUT: 3600
      CLIENT_MAX_BODY_SIZE: 200M
      WEBSOCKET: 'true'
    volumes:
      - ssl-certs:/var/lib/https-portal

volumes:
  ssl-certs: {}